config/routes.rb
Rails.application.routes.draw do

  resources :agencies
  get 'redirect', to: 'pages#redirect'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  resources :users, only: [:show]
  resources :searches do
    resources :announces do
      get 'visited_mail'
    end
    get 'mail_agency'
    get 'define_mail_agency'
  end

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul class="footerlist">
    <li><a class="social-link" href="mailto:t.rondio@free.fr"><i class="fa fa-envelope-o" aria-hidden="true"></i></a></li>
    <li><a class="social-link" href="tel:+33649840679" target="_blank"><i class="fa fa-phone" aria-hidden="true"></i></a></li>
    <li><a class="social-link" href="http://www.thomasrondio.com" target="_blank"><p>Site créé par TR</p></a></li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h1> BiensBiens - Paris </h1>
    <br style="height: 0;">
    <p> Faciliter votre projet d'achat </p>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hide-on-med-and-down">
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- dashboard_amin -->
      <%= link_to "Dashboard", user_path(current_user.id), class: "btn navbar-wagon-button" %>
      <!-- add_agency -->
      <%= link_to "+ agence", new_agency_path, class: "btn navbar-wagon-button " %>
      <!-- new_search -->
      <%= link_to "Nouvelle recherche", new_search_path(current_user.id), class: "btn navbar-wagon-button" %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <button class="btn navbar-wagon-button" data-toggle="dropdown"><%= current_user.user_name %></button>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_up", default: "Inscription"), new_user_registration_path, class: "btn-nb" %>
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "btn-nb" %>

    <% end %>
    </div>
    <!-- Dropdown list appearing on mobile only -->
      <div class="navbar-wagon-item hide-on-large-only">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% if user_signed_in? %>
              <% if current_user.admin? %>
                <li><%= link_to "Dashboard", user_path(current_user.id) %></li>
                <li><%= link_to "+ agence", new_agency_path %></li>
                <li><%= link_to "Nouvelle recherche", new_user_search_path(current_user.id) %></li>
              <% end %>
            <% else %>
              <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>


  <script>
    $(window).scroll(function() {
        var scroll = $(window).scrollTop();
        if (scroll >= 500) {
            $("#navbar").addClass("opacitylight");
        } else {
            $("#navbar").removeClass("opacitylight");
        }
    });
  </script>