config/routes.rb
Rails.application.routes.draw do

  resources :agencies
  get 'redirect', to: 'pages#redirect'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  resources :users, only: [:show]
  resources :searches do
    resources :announces do
      get 'visited_mail'
    end
    get 'mail_agency'
    get 'define_mail_agency'
  end

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # before_action :set_user
  before_action :set_search, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [ :new, :create ]


  def index
    @searches = Search.all
  end

  def define_mail_agency
    @search = Search.find(params['search_id'])
  end

  def mail_agency
    @count = 0
    @search = Search.find(params['search_id'])
    if @search.location.split(',').length >=2
      @search.location.split(',').each do |p|
        Agency.where(postal: p).each do |agency|
          if AgencyMailer.newsearch(agency, @search, @user).deliver_now
            @count += 1
          end
        end
      end
    else
      Agency.where(postal: @search.location).each do |agency|
        if AgencyMailer.newsearch(agency, @user, @search, ).deliver_now
          @count += 1
        end
      end
    end
    redirect_to user_search_path(@user, @search), notice: @count.to_s + ' mails was successfully sent.'
  end

  def show
    @announces = Announce.where(search_id: @search).reverse
    @partner_links = set_partner_links
  end

  def new
    if session[:form_data]
      Search.create(session[:form_data]['search'])
      redirect_to root_path, notice: 'La recherche a correctement été crée. Nous revenons vers vous très rapidement. '
    else
      @search = Search.new
      @user = User.find(current_user)
    end
  end

  def edit
  end

  def create
    if current_user.nil?
      @search = Search.new(search_params)
      @search.floor = params['search']['floor'].join(',').strip.gsub(/^,/, "")
      @search.location = params['search']['location'].join(',').strip.gsub(/^,/, "")
      @search.option = params['search']['option'].join(',').strip.gsub(/^,/, "")
      if @search.save
        cookies[:search_id] = {
              :value => @search.id,
              :expires => 1.year.from_now
            }
        redirect_to redirect_path(@search)
      else
        redirect_to root_path
      end
      cookies[:search_id] = {
            :value => 'a yummy cookie',
            :expires => 1.year.from_now,
            :domain => 'domain.com'
          }

    else
      @search = Search.new(search_params)
      @search.user_id = current_user.id
      @search.floor = params['search']['floor'].join(',').strip.gsub(/^,/, "") if params['search']['floor']
      @search.location = params['search']['location'].join(',').strip.gsub(/^,/, "") if params['search']['location']
      @search.option = params['search']['option'].join(',').strip.gsub(/^,/, "") if params['search']['option']
      respond_to do |format|
        if @search.save

          format.html {
            if user_signed_in?
              redirect_to user_search_url(current_user, @search), notice: 'Search was successfully created.'
            else
              redirect_to root_path, notice: 'La recherche a correctement été crée. Nous revenons vers vous très rapidement. '
            end
            }
          format.json { render :show, status: :created, location: @search }
        else
          format.html { render :new }
          format.json { render json: @search.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @search.update(search_params_update)
        format.html { redirect_to user_search_url(current_user), notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to user_searches_url(current_user), notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_search
    @search = Search.find(params[:id])
  end
  def set_user
    @user = User.find(current_user)
  end

  def search_params
    params.require(:search).permit(:price, :email, :username, :user_id, :lift, :surface, :room, :bedroom, :to_renovate, :comment, :option, location: [], floor: [])
  end

  def search_params_update
    if !params['search'].nil?
      if !@search.floor.nil? && !params['search']['floor'].nil?
        @search.floor = params['search']['floor'].join(',').strip.gsub(/^,/, "")
      end
      if !@search.location.nil? && !params['search']['location'].nil?
      @search.location = params['search']['location'].join(',').strip.gsub(/^,/, "")
      end
      if !@search.option.nil? && !params['search']['option'].nil?
      @search.option = params['search']['option'].join(',').strip.gsub(/^,/, "")
      end
    end
    params.require(:search).permit(:price, :email, :username, :user_id, :location, :floor, :lift, :surface, :room, :bedroom, :to_renovate, :comment, :text_for_agency, :option)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper

  def set_partner_links(search)
    @price_max = boncoin(@search.price)
    @surface_bc = boncoin_surface(@search.surface)
    partner_links = []
    # @search.location = JSON.parse(@search.location)
    # se_loger
    arrondissements = @search.location.gsub(/\ /,"").gsub('750', '7501')
    partner_links << "http://www.seloger.com/list.htm?org=advanced_search&pxmax=#{@search.price}&surfacemin=#{@search.surface}&idtt=2&idtypebien=1,2,9&ci=#{arrondissements}"
    # le bon coin
    if @search.location.split(',').length > 3
      @search.location.split(',').each_slice(3) do |slice|
        arrondissement_bc = slice.join(',').gsub(/\ /,"").gsub('750', 'Paris%20750').split(',').join('%2C')
        if !@price_max.nil?
          partner_links << "https://www.leboncoin.fr/ventes_immobilieres/offres/ile_de_france/?th=1&location=#{arrondissement_bc}&parrot=0&ps=#{@price_max - 4}&pe=#{@price_max}&sqs=#{@surface_bc}"
        end
      end
    else
      arrondissement_bc = @search.location.gsub(/\ /,"").gsub('750', 'Paris%20750').split(',').join('%2C')
      if !@price_max.nil?
        partner_links << "https://www.leboncoin.fr/ventes_immobilieres/offres/ile_de_france/?th=1&location=#{arrondissement_bc}&parrot=0&ps=#{@price_max - 4}&pe=#{@price_max}&sqs=#{@surface_bc}"
      end
    end
    # pap.fr
    par_arrondissement = []
    @search.location.split(',').each do |arr|
      postal = arr.to_i - 75000 + 37767
      par_arrondissement << "g" + postal.to_s
    end
    room = @search.room ? "-#{@search.room}-pieces" : ""
    bedroom = @search.bedroom ? "-#{@search.bedroom}-chambres" : ""
    partner_links << "http://www.pap.fr/annonce/vente-appartements-" + par_arrondissement.join + room + bedroom +"-jusqu-a-#{@search.price}-euros-a-partir-de-#{@search.surface}-m2"
    #logicimmo

    if @search.location.split(',').length > 3
      @search.location.split(',').each_slice(3) do |slice|
        li_arr = []
        slice.each do |postal|
          if postal == "75001"
            postal = "23599_2"
          elsif postal == "75009"
            postal = "23609_2"
          elsif postal.include?("7501")
            postal = (postal.to_i - 75010 + 23589).to_s + "_2"
          elsif postal == "75020"
            postal = "23600_2"
          else
            postal = (postal.to_i - 75000 + 23599).to_s + "_2"
          end
          li_arr << postal
        end
        partner_links << "http://www.logic-immo.com/vente-immobilier-paris,#{li_arr.join(',')}/options/groupprptypesids=1,2,6,7,12,15/pricemax=#{@search.price}/areamin=#{@search.surface}"
      end
    else
      li_arr = []
      @search.location.split(',').each do |postal|
        if postal == "75001"
          postal = "23599_2"
        elsif postal == "75020"
          postal = "23600_2"
        else
          postal = (postal.to_i - 75000 + 23599).to_s + "_2"
        end
        li_arr << postal
      end
    partner_links << "http://www.logic-immo.com/vente-immobilier-paris,#{li_arr.join(',')}/options/groupprptypesids=1,2,6,7,12,15/pricemax=#{@search.price}/areamin=#{@search.surface}"
    end
    return partner_links
  end

  def boncoin(price)
    price_max = price.to_i.round(-5).to_s
    price_bc = %w(0 25000 50000 75000 100000 125000 150000 175000 200000 225000 250000 275000 300000 325000 350000 400000 450000 500000 550000 600000 650000 700000 800000 900000 1000000 1100000 1200000 1300000 1400000 1500000 2000000)
    if price_bc.include?(price_max)
      price_max = price_bc.index(price_max)
    end
  end

  def boncoin_surface(surface)
    surface_max = surface.to_i.round(-1).to_s
    surface_bc = %w(0 20 25 30 35 40 50 60 70 80 90 100 110 120 130 140 150 200 300)
    if surface_bc.include?(surface_max)
      surface_max = surface_bc.index(surface_max)
    end
  end
end

app/views/searches/_form.html.erb
<%= simple_form_for([ current_user, @search]) do |f| %>
  <%= f.error_notification %>

  <% etages = %w(-1 rdc 1 2 3 4 5 6 7) %>
  <% options =["cheminee", "parquet", "baignoire", "balcon", "terrasse", "toilette separee", "cave", "parking", "calme", "ancien", "gardien"] %>
  <div class="form-inputs">
    <%= f.input :price, label: 'Prix maximum' %>
    <%= f.input :location, label: 'Arrondissements', as: :check_boxes, display: "inline-block",  collection: 75001..75020, input_html: { multiple: true } %>
    <%= f.input :floor, label: 'Etages', as: :check_boxes, display: "inline-block",  collection: etages, input_html: { multiple: true, checked: true }%>
    <%= f.input :lift, label: 'Ascenseur indispensable ?' %>
    <%= f.input :surface, label: 'Surface minimum' %>
    <%= f.input :room, label: 'Nombre de pièce minimum', collection: 1..10 %>
    <%= f.input :bedroom, label: 'Nombre de chambre minimum', collection: 1..10 %>
    <%= f.input :to_renovate, label: 'Travaux', collection: ["Pourquoi pas", "Hors de question"] %>
    <%= f.input :comment, label: 'Vos précisions' %>
    <%#= f.input :text_for_agency, label: 'agency-mailer' %>
    <%= f.input :option, as: :text, label: 'Options', as: :check_boxes, display: "inline-block",  collection: options, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "C'est parti !", class: "btn btn-primary btn-lg btn-block" %>
  </div>

<% end %>

app/views/searches/define_mail_agency.html.erb
<div class="container home" >
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <%= render 'agency_mailer/bodymail', search: @search %>

      <%= simple_form_for([current_user, @search], html: {id: :edit_text_for_agency }) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :text_for_agency, label: 'Modifiez à vos souhaits ce mail', class: 'large-form', input_html: {value: (render 'agency_mailer/defaultmail', search: @search) }%>
        </div>
        <div class="form-actions">
          <%= f.button :submit, "Apercu", class: "btn btn-primary btn-lg btn-block", input_html: {href: user_search_define_mail_agency_path(current_user, @search) }, notice: 'Search was successfully updated.' %>
        </div>



      <%= link_to "C'est parti !", user_search_mail_agency_url(@user, params['search_id']), class: "btn btn-primary btn-lg btn-block", id: "form_email" %>
      <% end %>

      <h1 class="text-center">La recherche de <%= @search.username%></h1>

      <h3 class="text-justify"><%= @search.username%> cherche un bien à maximum <%= @search.price %> €, dans les arrondissements suivants :
        <%= @search.location.split(",").join(', ') %>
      </h3>

      <p>
        étages désirés : <%= @search.floor.split(",").join(', ') %>
      </p>

      <p>
        <% if @search.lift %>
        <strong>La présence d'un ascenseur indispensable</strong>
        <% end %>
      </p>
      <p>
        <% if @search.to_renovate %>
        <strong>Les travaux ne dérangent pas <%= @search.username%> </strong>
        <% end %>
      </p>

      <p>
        <strong>Surface:</strong>
        <%= @search.surface %>
      </p>

      <p>
        <strong>Nombre de pièce:</strong>
        <%= @search.room %>
      </p>

      <p>
        <strong>Nombre de chambre:</strong>
        <%= @search.bedroom %>
      </p>

         <p>
        <strong>Options demandées:</strong>
        <%= @search.option %>
      </p>


      <p>
        <strong>Commentaires:</strong>
        <%= @search.comment %>
      </p>
    </div>
  </div>
</div>
<!-- <script type="text/javascript">
$(function() {
    $('#edit_text_for_agency').on('submit', function(e) {
          e.preventDefault();
          setTimeout(function() {
               window.location.reload();
          },0);
          this.submit();
    });
});
</script> -->

app/views/searches/edit.html.erb
<div class="container home" >
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Editing Search</h1>

      <%= render 'form', search: @search %>

      <%= link_to 'Show', user_search_path(current_user, @search) %> |
      <%= link_to 'Back', user_searches_path(current_user) %>

    </div>
  </div>
</div>


<% if !@search.location.nil? %>
  <%= javascript_tag do %>
    <% @search.location.split(',').each do |p| %>
      document.getElementById("<%="search_location_#{p}"%>").checked = true;
    <% end %>
  <% end %>
<% end %>

<% if !@search.floor.nil? %>
  <%= javascript_tag do %>
    <% @search.floor.split(',').each do |p| %>
      document.getElementById("<%="search_floor_#{p}"%>").checked = true;
    <% end %>
  <% end %>
<% end %>

<% if !@search.option.nil? %>
  <%= javascript_tag do %>
    <% @search.option.split(',').each do |p| %>
      document.getElementById("<%="search_option_#{p}"%>").checked = true;
    <% end %>
  <% end %>
<% end %>

app/views/searches/index.html.erb
<div class="container home" >
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <p id="notice"><%= notice %></p>

      <h1>Searches</h1>

      <table>
        <thead>
          <tr>
            <th>Price</th>
            <th>Location</th>
            <th>Floor</th>
            <th>Lift</th>
            <th>Surface</th>
            <th>Room</th>
            <th>Bedroom</th>
            <th>To renovate</th>
            <th>Comment</th>
            <th>Option</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @searches.each do |search| %>
            <tr>
              <td><%= search.price %></td>
              <td><%= search.location %></td>
              <td><%= search.floor %></td>
              <td><%= search.lift %></td>
              <td><%= search.surface %></td>
              <td><%= search.room %></td>
              <td><%= search.bedroom %></td>
              <td><%= search.to_renovate %></td>
              <td><%= search.comment %></td>
              <td><%= search.option %></td>
              <td><%= link_to 'Show', user_search_path(current_user.id, search.id) %></td>
              <td><%= link_to 'Edit', edit_user_search_path(current_user.id, search) %></td>
              <td><%= link_to 'Destroy', user_search_path(current_user.id, search), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Search', new_user_search_path %>

    </div>
  </div>
</div>

app/views/searches/new.html.erb
<div class="container home" >
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Nouvelle recherche</h1>

      <%= render 'form', user: @user, search: @search %>

      <%= link_to 'Back', user_searches_path %>
    </div>
  </div>
</div>

app/views/searches/show.html.erb
<div class="container home" >
  <div class="row">
    <p id="notice"><%= notice %></p>
    <div class="col-xs-12 col-sm-4">
      <%= link_to 'Ajouter un nouvel appartement', new_user_search_announce_path(current_user, @search), class: 'btn btn-primary navigate' %>
    </div>
    <div class="col-xs-12 col-sm-4">
    <a href="#" class: 'btn btn-primary navigate' onclick="<% @partner_links.each do |pl|%> window.open('<%=pl%>'); <% end %> return true;">Lancer la recherche sur nos sites partenaires</a>
    </div>


      <%= link_to 'Envoyer un mail a toutes les agences', user_search_define_mail_agency_url(current_user, @search) %> |
      <%= link_to 'Modifiez', edit_user_search_path %> |
      <%= link_to 'Retour', user_path(current_user) %>

      <h1 class="text-center">La recherche de <%= @search.username%></h1>

      <h3 class="text-justify"><%= @search.username%> cherche un bien à maximum <%= @search.price %> €, dans les arrondissements suivants :
        <%= @search.location.split(",").join(', ') %>
      </h3>

      <p>
        étages désirés : <%= @search.floor.split(",").join(', ') %>
      </p>

      <p>
        <% if @search.lift %>
        <strong>La présence d'un ascenseur indispensable</strong>
        <% end %>
      </p>
      <p>
        <% if @search.to_renovate %>
        <strong>Les travaux ne dérangent pas <%= @search.username%> </strong>
        <% end %>
      </p>

      <p>
        <strong>Surface:</strong>
        <%= @search.surface %>
      </p>

      <p>
        <strong>Nombre de pièce:</strong>
        <%= @search.room %>
      </p>

      <p>
        <strong>Nombre de chambre:</strong>
        <%= @search.bedroom %>
      </p>

         <p>
        <strong>Options demandées:</strong>
        <%= @search.option %>
      </p>


      <p>
        <strong>Commentaires:</strong>
        <%= @search.comment %>
      </p>


      <% @announces.each do |a| %>
        <%= link_to user_search_announce_path(current_user, @search, a), class: "announce-card" do %>

        <div class="background-appt" style="background-image: linear-gradient(135deg, rgba(205,237,47,0.5) 0%,rgba(83,109,20,0.8) 50%), url(<%= a.photos.nil? ? "http://www.kadences-deco.fr/wp-content/uploads/2015/07/appartement-design-730x430.jpg" : a.photos.split(',').first %>)">
          <h1><%= a.address.upcase %></h1>
          <p><%= a.status %></p>
        </div>
        <%= link_to 'Modifier', edit_user_search_announce_path(current_user, @search, a), class: "btn navigate navigate-grey" %>
        <%= link_to 'Supprimer', user_search_announce_path(current_user, @search, a), class: "btn navigate navigate-grey", method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
<!-- background-image: linear-gradient(135deg, rgba(205,237,47,1) 0%,rgba(83,109,20,1) 50%,rgba(199,232,37,1) 100%,rgba(125,185,232,1) 100%,rgba(32,124,202,1) 100%) -->

    </div>
  </div>
</div>